# Docker hub构建并推送示例，请替换用户名和密钥，手动触发，自动推送
name: Docker-hub构建并推送

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
   
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}/${{ github.event.inputs.version }}
          tags: |
            type=manual

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # 用户名和密钥的变量
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # 这里的点代表仓库的根目录，如果需要更改子目录则更改这里即可，例如：./node
          context: .
          push: true
          # 注意你的基础镜像有没有下列架构
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.repository }}:${{ github.event.inputs.version }}, ${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
