# Docker hub构建并推送，需指定用户名和密钥变量，手动触发，自动推送
name: Docker-hub构建并推送
on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
        default: 'latest'
      image_name:
        description: 'Docker镜像名称（不含用户名）'
        required: true
        default: 'myimage'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
   
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.image_name }}
          tags: |
            ${{ github.event.inputs.version }}
            latest
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # 结尾的点代表仓库的根目录，可以更改为子目录，例如：./src
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
